"""Alembic's env.py must see every model module.

`target_metadata = Base.metadata` is what `alembic revision --autogenerate`
diffs the live database against. A model module that env.py never imports leaves
its table out of that metadata — and autogenerate, seeing a table in the database
that "no model declares", proposes to DROP it.

That was not hypothetical: `migration_executions` (0008) shipped without its
import here, so the next autogenerated revision would have dropped the execution
history. The failure mode is silent at review time and destructive at run time,
which is exactly the kind that needs a test rather than a convention.
"""

from __future__ import annotations

from pathlib import Path

_API_ROOT = Path(__file__).resolve().parents[2]
_ENV_PY = _API_ROOT / "alembic" / "env.py"
_MODULES = _API_ROOT / "app" / "modules"


def _modules_that_declare_a_table() -> set[str]:
    return {
        models.parent.name
        for models in _MODULES.glob("*/models.py")
        if "__tablename__" in models.read_text()
    }


def test_every_model_module_is_imported_by_alembic_env() -> None:
    declared = _modules_that_declare_a_table()
    assert declared, "no model modules found — the glob is wrong, not the code"

    env_source = _ENV_PY.read_text()
    missing = {
        name
        for name in declared
        if f"from app.modules.{name} import models" not in env_source
    }
    assert not missing, (
        f"alembic/env.py does not import {sorted(missing)}: their tables are absent "
        "from target_metadata, so an --autogenerate revision would DROP them"
    )
